PROPERTIES = {
    "PROP-BCN-001": {
        "property_id": "PROP-BCN-001",
        "name": "Apartamentos Gran Via Barcelona",
        "city": "Barcelona",
        "country": "Spain",
        "address": "Gran Via de les Corts Catalanes 450, 08015 Barcelona",
        "stars": 4,
        "type": "aparthotel",
        "check_in_time": "15:00",
        "check_out_time": "11:00",
        "early_checkin_available": True,
        "late_checkout_available": True,
        "reception_hours": "24/7",
        "self_checkin": False,
        "amenities": {
            "wifi": {"available": True, "speed_mbps": 100, "cost": "free"},
            "parking": {"available": True, "cost": "18 EUR/day", "reservation_required": True},
            "gym": {"available": True, "hours": "06:00-22:00"},
            "pool": {"available": False},
            "laundry": {"available": True, "type": "coin-operated", "floor": 2},
            "kitchen": {
                "available": True,
                "type": "full_kitchen",
                "equipment": ["dishwasher", "microwave", "oven", "coffee_machine"],
            },
            "cleaning": {"frequency": "weekly", "included": True},
            "air_conditioning": True,
            "elevator": True,
            "pets_allowed": False,
            "smoking_allowed": False,
        },
        "contact": {
            "phone": "+34 93 000 0001",
            "email": "granvia@stayforlong.com",
            "whatsapp": "+34 600 000 001",
        },
        "local_transport": {
            "metro": "Urgell (L1) - 3 min walk",
            "bus": "Lines 9, 27, 50",
            "airport_shuttle": False,
        },
        "stayforlong_rating": 4.7,
        "total_reviews": 312,
    },
    "PROP-MAD-003": {
        "property_id": "PROP-MAD-003",
        "name": "Residencia Salamanca Madrid",
        "city": "Madrid",
        "country": "Spain",
        "address": "Calle de Serrano 88, 28006 Madrid",
        "stars": 4,
        "type": "serviced_apartment",
        "check_in_time": "14:00",
        "check_out_time": "12:00",
        "early_checkin_available": False,
        "late_checkout_available": True,
        "reception_hours": "08:00-22:00",
        "self_checkin": True,
        "self_checkin_method": "Key lockbox - code sent 24h before arrival",
        "amenities": {
            "wifi": {"available": True, "speed_mbps": 200, "cost": "free"},
            "parking": {"available": False, "nearby_garage": "SABA Serrano - 5 min walk"},
            "gym": {"available": False, "nearby_gym": "Holmes Place - partner discount"},
            "pool": {"available": False},
            "laundry": {"available": True, "type": "in-unit washer/dryer"},
            "kitchen": {"available": True, "type": "full_kitchen"},
            "cleaning": {"frequency": "bi-weekly", "included": True},
            "air_conditioning": True,
            "elevator": True,
            "pets_allowed": True,
            "pets_policy": "Max 2 pets, max 15kg each. 100 EUR deposit required.",
            "smoking_allowed": False,
        },
        "contact": {
            "phone": "+34 91 000 0003",
            "email": "salamanca@stayforlong.com",
        },
        "stayforlong_rating": 4.5,
        "total_reviews": 198,
    },
    "PROP-LIS-002": {
        "property_id": "PROP-LIS-002",
        "name": "LX Factory Residences Lisboa",
        "city": "Lisbon",
        "country": "Portugal",
        "address": "Rua Rodrigues de Faria 103, 1300-501 Lisboa",
        "stars": 3,
        "type": "aparthotel",
        "check_in_time": "16:00",
        "check_out_time": "11:00",
        "early_checkin_available": True,
        "late_checkout_available": False,
        "reception_hours": "07:00-23:00",
        "self_checkin": False,
        "amenities": {
            "wifi": {"available": True, "speed_mbps": 50, "cost": "free"},
            "parking": {"available": True, "cost": "12 EUR/day"},
            "gym": {"available": False},
            "pool": {"available": False},
            "laundry": {"available": True, "type": "shared laundry room", "floor": 1},
            "kitchen": {"available": True, "type": "kitchenette"},
            "cleaning": {"frequency": "weekly", "included": True},
            "air_conditioning": True,
            "elevator": False,
            "pets_allowed": True,
            "smoking_allowed": False,
        },
        "contact": {
            "phone": "+351 21 000 0002",
            "email": "lxfactory@stayforlong.com",
        },
        "stayforlong_rating": 4.3,
        "total_reviews": 87,
    },
}

# Name aliases for fuzzy lookup
PROPERTY_ALIASES = {
    "gran via": "PROP-BCN-001",
    "barcelona": "PROP-BCN-001",
    "bcn": "PROP-BCN-001",
    "salamanca": "PROP-MAD-003",
    "madrid": "PROP-MAD-003",
    "mad": "PROP-MAD-003",
    "lx factory": "PROP-LIS-002",
    "lisboa": "PROP-LIS-002",
    "lisbon": "PROP-LIS-002",
    "lis": "PROP-LIS-002",
}
