RESERVATIONS = {
    "SFL-2024-001": {
        "booking_id": "SFL-2024-001",
        "guest_name": "Carlos Martinez",
        "email": "carlos.m@email.com",
        "property_id": "PROP-BCN-001",
        "property_name": "Apartamentos Gran Via Barcelona",
        "check_in": "2024-03-15",
        "check_out": "2024-04-12",
        "nights": 28,
        "room_type": "Studio Apartment",
        "total_price": 2240.00,
        "currency": "EUR",
        "status": "confirmed",
        "payment_status": "paid",
        "cancellation_policy": "flexible",
        "cancellation_deadline": "2024-03-10",
        "special_requests": "Late check-in requested (after 22:00)",
    },
    "SFL-2024-002": {
        "booking_id": "SFL-2024-002",
        "guest_name": "Sophie Dubois",
        "email": "sophie.d@email.com",
        "property_id": "PROP-MAD-003",
        "property_name": "Residencia Salamanca Madrid",
        "check_in": "2024-02-01",
        "check_out": "2024-02-29",
        "nights": 28,
        "room_type": "One-Bedroom Apartment",
        "total_price": 3080.00,
        "currency": "EUR",
        "status": "checked_in",
        "payment_status": "paid",
        "cancellation_policy": "strict",
        "cancellation_deadline": "2024-01-18",
        "special_requests": None,
    },
    "SFL-2024-003": {
        "booking_id": "SFL-2024-003",
        "guest_name": "James Wilson",
        "email": "james.w@email.com",
        "property_id": "PROP-LIS-002",
        "property_name": "LX Factory Residences Lisboa",
        "check_in": "2024-04-01",
        "check_out": "2024-04-30",
        "nights": 29,
        "room_type": "Studio Apartment",
        "total_price": 1740.00,
        "currency": "EUR",
        "status": "pending",
        "payment_status": "partially_paid",
        "cancellation_policy": "moderate",
        "cancellation_deadline": "2024-03-25",
        "special_requests": "Pet-friendly room required",
    },
}

EMAIL_INDEX = {r["email"]: r for r in RESERVATIONS.values()}

CANCELLATION_POLICIES = {
    "flexible": "Cancellación gratuita hasta 5 días antes del check-in. Después: reembolso del 50%.",
    "moderate": "Cancellación gratuita hasta 7 días antes. Entre 7 y 3 días: reembolso del 50%. Menos de 3 días: sin reembolso.",
    "strict": "Cancellación gratuita hasta 14 días antes. Entre 14 y 7 días: reembolso del 25%. Menos de 7 días: sin reembolso.",
}
